@extends('admin.layout')

@section('content')
<div class="admin-shell">
    @include('admin.partials.sidebar', ['activeAdminNav' => 'invoices'])

    <div class="admin-main admin-management-main">
        <section class="admin-page-head">
            <div>
                <h1 class="admin-page-title">Invoices</h1>
                <p class="admin-page-copy">Track invoice-style order records generated by customer purchases.</p>
            </div>
        </section>

        <section class="panel admin-list-panel">
            <div class="table-wrap">
                <table class="admin-data-table">
                    <thead>
                    <tr>
                        <th>Invoice</th>
                        <th>Customer</th>
                        <th>Status</th>
                        <th>Total</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($orders as $order)
                        <tr>
                            <td>{{ $order->order_number }}</td>
                            <td>{{ $order->user?->name ?? $order->shipping_name }}</td>
                            <td>{{ ucfirst($order->status) }}</td>
                            <td>{{ number_format((float) $order->total_amount, 2) }} KES</td>
                            <td>{{ $order->created_at?->format('d/m/Y') }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="admin-empty-cell">No invoices yet.</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
@endsection
